max_width = 80
tab_spaces = 4
match_block_trailing_comma = true
newline_style = "Unix"

merge_derives = true

remove_nested_parens = true
reorder_imports = true
reorder_modules = true
use_field_init_shorthand = true

# Non-stable
#brace_style = "SameLineWhere"
